### PR TITLE
Made service configuration lazy (allow export from wrapper cookbooks).

### PR DESCRIPTION
**Pull request by jperville**
This simple PR to allows wrapper cookbooks to export services to `node.force_default['newrelic_meetme_plugin']['services']`.

Here is how I use the cookbook:
 - each recipe that installs services supported by meetme writes an entry into `node.force_default['newrelic_meetme_plugin']['services']`
 - when `recipe[newrelic_meetme_plugin]` runs, it collects all the services and dumps them into the meetme configuration files.

I use `node.force_default` instead of `node.default` to not depend on cookbook order in the run list.
Without the 'lazy' part, only services known at compile-time will be included, preventing dynamic export of meetme service entries in wrapper cookbooks.

Note: the services entries cannot be written in attributes (as with a role) because the service is not installed on all nodes, so they should only be monitored where they are is installed.

### CODE REVIEW

**Comment by jperville** [comment]
The travis build failure is unrelated to this PR, I submitted #13 to fix it.

**Comment by djoos** [comment]
Hi @jperville,

I'd rather look into turning the recipe of this cookbook into LWRP(s) to get round the issue you are experiencing. That way you can use the LWRP in your wrapper cookbook instead...

What do you think?

Kind regards,
David

**Comment by jperville** [comment]
I like LWRPs, thank you @djoos.

**Comment by djoos** [comment]
Hi @jperville,

as per @lmunro's work in #20, you should now have a more elegant way to get round your issue.

Hope this helps!

Kind regards,
David

**Comment by jperville** [comment]
Thank you very much @djoos

**Pull request closed without merging**
